package chapter18;

public class TryCatchRuntimeException2 {
	
	public static void main(String[] args) {
		try {
			System.out.println("예외 발생 전 코드");
//			System.out.println(value1);
			int value1 = Integer.parseInt("a100");
			System.out.println("예외 발생 후 코드");
		} catch (StringIndexOutOfBoundsException e) {
			System.out.println("종료");
		}
	}
}
